name: Build and Push Docker Image

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sys-src/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker Compose image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: goalguru
          IMAGE_TAG: latest
        run: |
          # Build Docker Compose image
          docker compose up --build

          # Tag image
          docker tag goalguru:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Push image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          

