name: Run all tests (CI part)

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Backend setup and tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      working-directory: ./sys-src/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest with coverage
      working-directory: ./sys-src/backend
      run: pytest tests

    # Frontend setup, tests, and linting
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./sys-src/frontend
      run: npm ci

    - name: Run tests
      working-directory: ./sys-src/frontend
      run: npm run test:coverage

    - name: Run linting
      working-directory: ./sys-src/frontend
      run: npm run lint

