name: Run all tests

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Backend setup and tests
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      working-directory: ./sys-src/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest with coverage
      working-directory: ./sys-src/backend
      run: pytest
      #continue-on-error: true

    # Frontend setup und testing
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./sys-src/frontend
      run: npm ci

    - name: Run tests
      working-directory: ./sys-src/frontend
      run: npm run test:coverage

